# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define :scm do |scm|
    scm.vm.box = "centos-6.5"
    scm.vm.hostname="scmserver"
    scm.vm.network "private_network", ip: "192.168.56.201"
    scm.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512"]
    end
    scm.vm.synced_folder "../ansible", "/app/ansible",
    create: true, owner: "vagrant", group: "vagrant"
    scm.vm.synced_folder "../resources", "/app/resources",
    create: true, owner: "vagrant", group: "vagrant"
  end

  # chefのインストール
  ## インターネット経由
  #config.omnibus.chef_version = "12.0.1"
  ## オフライン(rpmを配置すること)
  #config.vm.provision :shell, :inline => "if ! rpm -qa | grep -q chef; then rpm -ivh /vagrant/chef-12.0.1-1.x86_64.rpm; fi" 

  #config.vm.provision "chef_solo" do |chef|
  #  chef.cookbooks_path = "../chef-repo/cookbooks"
  #end

  # ansibleのインストール
  config.vm.provision :shell, :inline => "yum install -y ansible"

  #config.vm.provision :ansible do |ansible|
  #  ansible.playbook = "/app/ansible/main.yml"  # 作成したplaybookファイル名
  #  ansible.inventory_path = "hosts"  # 作成したインベントリーファイル名
  #end

end
